spring.application.name=player-services
server.port=${PLAYER_SERVICE_PORT:8081}
riot.api.key=${RIOT_API_KEY}
riot.api.base-url=${RIOT_API_BASE_URL}
match.service.base-url=${MATCH_PLAYER_SERVICE_URL:http://localhost:8082}