version: '3.8'
services:
  lol-match-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=micros
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - RIOT_API_KEY=${RIOT_API_KEY}
      - RIOT_API_BASE_URL=https://europe.api.riotgames.com/
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=micros
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
