version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-micro
    restart: always
    environment:
      POSTGRES_DB: micros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  match-history-service:
    build:
      context: ../../../../
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: match_history
      DB_USER: postgres
      DB_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  pgdata:
