CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    game_name VARCHAR(64) NOT NULL,
    tag_line VARCHAR(32) NOT NULL,
    platform VARCHAR(16) DEFAULT 'EUW1' NOT NULL,
    puuid VARCHAR(128),
    active BOOLEAN DEFAULT TRUE NOT NULL,
    archived_at TIMESTAMP(6) WITH TIME ZONE,
    last_polled_at TIMESTAMP(6) WITH TIME ZONE,
    track_from TIMESTAMP(6) WITH TIME ZONE,
    backfill_mode VARCHAR(40) DEFAULT 'NONE' NOT NULL,
    last_successful_sync_at TIMESTAMP(6) WITH TIME ZONE,
    last_sync_status VARCHAR(32),
    last_error VARCHAR(500),
    rank_queue_type VARCHAR(32),
    rank_tier VARCHAR(24),
    rank_division VARCHAR(8),
    rank_league_points INTEGER,
    rank_score INTEGER,
    rank_updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_players PRIMARY KEY (id)
);

ALTER TABLE players ADD COLUMN IF NOT EXISTS platform VARCHAR(16) DEFAULT 'EUW1' NOT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS puuid VARCHAR(128);
ALTER TABLE players ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_polled_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS track_from TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS backfill_mode VARCHAR(40) DEFAULT 'NONE' NOT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_successful_sync_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_sync_status VARCHAR(32);
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_error VARCHAR(500);
ALTER TABLE players ADD COLUMN IF NOT EXISTS rank_queue_type VARCHAR(32);
ALTER TABLE players ADD COLUMN IF NOT EXISTS rank_tier VARCHAR(24);
ALTER TABLE players ADD COLUMN IF NOT EXISTS rank_division VARCHAR(8);
ALTER TABLE players ADD COLUMN IF NOT EXISTS rank_league_points INTEGER;
ALTER TABLE players ADD COLUMN IF NOT EXISTS rank_score INTEGER;
ALTER TABLE players ADD COLUMN IF NOT EXISTS rank_updated_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;
UPDATE players SET puuid = NULL WHERE puuid IS NOT NULL AND TRIM(puuid) = '';

CREATE TABLE IF NOT EXISTS tracked_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id BIGINT NOT NULL,
    match_id VARCHAR(64) NOT NULL,
    champion_name VARCHAR(64) DEFAULT 'Unknown' NOT NULL,
    champion_id INTEGER,
    result VARCHAR(16) DEFAULT 'UNKNOWN' NOT NULL,
    game_mode VARCHAR(64) DEFAULT 'Unknown' NOT NULL,
    queue_id INTEGER,
    lane VARCHAR(32),
    role VARCHAR(32),
    kills INTEGER DEFAULT 0 NOT NULL,
    deaths INTEGER DEFAULT 0 NOT NULL,
    assists INTEGER DEFAULT 0 NOT NULL,
    creep_score INTEGER DEFAULT 0 NOT NULL,
    gold_earned INTEGER DEFAULT 0 NOT NULL,
    damage_dealt_to_champions INTEGER DEFAULT 0 NOT NULL,
    vision_score INTEGER DEFAULT 0 NOT NULL,
    duration_seconds BIGINT DEFAULT 0 NOT NULL,
    game_end_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    platform VARCHAR(32),
    region VARCHAR(32),
    notification_sent BOOLEAN DEFAULT FALSE NOT NULL,
    notification_sent_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_tracked_matches PRIMARY KEY (id),
    CONSTRAINT fk_tracked_matches_player FOREIGN KEY (player_id) REFERENCES players (id)
);

ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS champion_name VARCHAR(64) DEFAULT 'Unknown' NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS champion_id INTEGER;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS result VARCHAR(16) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS game_mode VARCHAR(64) DEFAULT 'Unknown' NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS queue_id INTEGER;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS lane VARCHAR(32);
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS role VARCHAR(32);
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS kills INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS deaths INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS assists INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS creep_score INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS gold_earned INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS damage_dealt_to_champions INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS vision_score INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS duration_seconds BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS game_end_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS platform VARCHAR(32);
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS region VARCHAR(32);
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS notification_sent BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS notification_sent_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE tracked_matches ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    match_id VARCHAR(64) NOT NULL,
    game_mode VARCHAR(64) DEFAULT 'Unknown' NOT NULL,
    queue_id INTEGER,
    duration_seconds BIGINT DEFAULT 0 NOT NULL,
    game_end_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    platform VARCHAR(32),
    region VARCHAR(32),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_matches PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS player_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id BIGINT NOT NULL,
    match_id BIGINT NOT NULL,
    puuid VARCHAR(128) NOT NULL,
    champion_id INTEGER,
    champion_name VARCHAR(64) DEFAULT 'Unknown' NOT NULL,
    result VARCHAR(16) DEFAULT 'UNKNOWN' NOT NULL,
    lane VARCHAR(32),
    role VARCHAR(32),
    kills INTEGER DEFAULT 0 NOT NULL,
    deaths INTEGER DEFAULT 0 NOT NULL,
    assists INTEGER DEFAULT 0 NOT NULL,
    creep_score INTEGER DEFAULT 0 NOT NULL,
    gold_earned INTEGER DEFAULT 0 NOT NULL,
    damage_dealt_to_champions INTEGER DEFAULT 0 NOT NULL,
    vision_score INTEGER DEFAULT 0 NOT NULL,
    notification_suppressed BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_player_matches PRIMARY KEY (id),
    CONSTRAINT fk_player_matches_player FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE CASCADE,
    CONSTRAINT fk_player_matches_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tracked_match_id BIGINT NOT NULL,
    status VARCHAR(16) DEFAULT 'PENDING' NOT NULL,
    attempt_count INTEGER DEFAULT 0 NOT NULL,
    last_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    next_attempt_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_error VARCHAR(500),
    telegram_message_id INTEGER,
    sent_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_notification_outbox PRIMARY KEY (id),
    CONSTRAINT fk_notification_outbox_tracked_match FOREIGN KEY (tracked_match_id) REFERENCES tracked_matches (id)
);

CREATE TABLE IF NOT EXISTS external_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    integration VARCHAR(24) NOT NULL,
    operation VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    category VARCHAR(32),
    summary VARCHAR(500),
    occurred_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_external_call_logs PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS poll_locks (
    name VARCHAR(64) NOT NULL,
    owner VARCHAR(128),
    locked_until TIMESTAMP(6) WITH TIME ZONE,
    acquired_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT,
    CONSTRAINT pk_poll_locks PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS poll_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP(6) WITH TIME ZONE,
    status VARCHAR(32) NOT NULL,
    owner VARCHAR(128),
    current_player VARCHAR(160),
    current_stage VARCHAR(120),
    rate_limit_paused_until TIMESTAMP(6) WITH TIME ZONE,
    rate_limit_message VARCHAR(500),
    players_processed INTEGER DEFAULT 0 NOT NULL,
    new_matches_found INTEGER DEFAULT 0 NOT NULL,
    notifications_sent INTEGER DEFAULT 0 NOT NULL,
    error_summary VARCHAR(500),
    CONSTRAINT pk_poll_runs PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS app_configuration (
    id BIGINT NOT NULL,
    riot_api_key VARCHAR(1200),
    riot_region VARCHAR(32) DEFAULT 'EUROPE' NOT NULL,
    telegram_bot_token VARCHAR(1200),
    telegram_chat_id VARCHAR(1200),
    polling_enabled BOOLEAN,
    polling_manual_only BOOLEAN,
    polling_fixed_delay VARCHAR(32),
    polling_match_window_size INTEGER,
    polling_pagination_limit INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_app_configuration PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_players_identity ON players (game_name, tag_line);
CREATE UNIQUE INDEX IF NOT EXISTS idx_players_puuid ON players (puuid);
CREATE INDEX IF NOT EXISTS idx_players_active_archived ON players (active, archived_at);
CREATE INDEX IF NOT EXISTS idx_players_track_from ON players (track_from);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tracked_matches_player_match ON tracked_matches (player_id, match_id);
CREATE INDEX IF NOT EXISTS idx_tracked_matches_player_end ON tracked_matches (player_id, game_end_at);
CREATE INDEX IF NOT EXISTS idx_tracked_matches_match_id ON tracked_matches (match_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_matches_match_id ON matches (match_id);
CREATE INDEX IF NOT EXISTS idx_matches_game_end_at ON matches (game_end_at);
CREATE INDEX IF NOT EXISTS idx_matches_platform_region ON matches (platform, region);

CREATE UNIQUE INDEX IF NOT EXISTS ux_player_matches_player_match ON player_matches (player_id, match_id);
CREATE INDEX IF NOT EXISTS idx_player_matches_player_result ON player_matches (player_id, result);
CREATE INDEX IF NOT EXISTS idx_player_matches_match ON player_matches (match_id);
CREATE INDEX IF NOT EXISTS idx_player_matches_champion ON player_matches (champion_name);

CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_outbox_tracked_match ON notification_outbox (tracked_match_id);
CREATE INDEX IF NOT EXISTS idx_notification_outbox_status_next_attempt ON notification_outbox (status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_notification_outbox_created_at ON notification_outbox (created_at);

CREATE INDEX IF NOT EXISTS idx_external_call_logs_integration_status
    ON external_call_logs (integration, status, occurred_at);
CREATE INDEX IF NOT EXISTS idx_external_call_logs_occurred_at ON external_call_logs (occurred_at);
