CREATE TABLE IF NOT EXISTS player_rank_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id BIGINT NOT NULL,
    queue_type VARCHAR(32) NOT NULL,
    tier VARCHAR(24) NOT NULL,
    division VARCHAR(8) NOT NULL,
    league_points INTEGER DEFAULT 0 NOT NULL,
    score INTEGER DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_player_rank_snapshots PRIMARY KEY (id),
    CONSTRAINT fk_player_rank_snapshots_player FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_player_rank_snapshots_player_queue
    ON player_rank_snapshots (player_id, queue_type);

CREATE INDEX IF NOT EXISTS idx_player_rank_snapshots_queue_score
    ON player_rank_snapshots (queue_type, score);

INSERT INTO player_rank_snapshots (
    player_id,
    queue_type,
    tier,
    division,
    league_points,
    score,
    updated_at
)
SELECT
    player.id,
    player.rank_queue_type,
    player.rank_tier,
    player.rank_division,
    player.rank_league_points,
    player.rank_score,
    COALESCE(player.rank_updated_at, CURRENT_TIMESTAMP)
FROM players player
WHERE player.rank_queue_type IS NOT NULL
  AND player.rank_tier IS NOT NULL
  AND player.rank_division IS NOT NULL
  AND player.rank_league_points IS NOT NULL
  AND player.rank_score IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM player_rank_snapshots existing
      WHERE existing.player_id = player.id
        AND existing.queue_type = player.rank_queue_type
  );
